"""Add user_id to Application

Revision ID: 6f8ac59dbc17
Revises: 
Create Date: 2025-05-09 00:08:35.597505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8ac59dbc17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_link', sa.String(length=255), nullable=True))
        batch_op.drop_column('resume_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('resume_link')

    # ### end Alembic commands ###
